# Creates/Resets the gh-pages branch to the intended start state

name: "00-gh-pages-create: Create GH pages site"
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write
  pages: write
  id-token: write
  administration:write 

jobs: 
  enable-github-pages:
    name: Enable Github Pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v2

    - name: Github API Call
      run: |
         gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ucsb-cs156-s23/STARTER-jpa03/pages \
            -f buildtype=workflow
  