# Creates/Resets the gh-pages branch to the intended start state

name: "01-gh-pages-reset: Create or reset gh-pages branch"
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write  # Needed for JamesIves/github-pages-deploy-action@v4

jobs: 
  build-site:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v2

    - name: Append name of site to _config.yml
      run: | 
          CONFIG_YML=frontend/docs-index/_config.yml
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          echo "repo: ${OWNER_PLUS_REPOSITORY}" >> ${CONFIG_YML}
          echo "owner: ${OWNER}" >> ${CONFIG_YML}
          echo "repo_name: ${REPOSITORY}" >> ${CONFIG_YML}

    - name: Compose web site
      run: |
        mkdir site
        cp -r frontend/docs-index/* site    

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site # The folder the action should deploy.
        branch: gh-pages
        clean: true # Automatically remove deleted files from the deploy branch
