name: "02-gh-pages-prs: Create or reset PR collection"
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write  # Needed for JamesIves/github-pages-deploy-action@v4

jobs: 
  setup-node-and-cache-it:
    name: Setup Node.js (and cache it)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json


  get-pull-requests:
    name: Get Pull Requests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Get branches from Github api
      run: |
         gh pr list -s open --json url,author,number,title,headRefName > prs.json
         PRS=`cat prs.json`
         echo "PRS=${PRS}" >> "$GITHUB_OUTPUT"

  build-basic-site:
    name: Build Basic Site
    runs-on: ubuntu-latest
    needs: [get-pull-requests]

    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Append name of site to _config.yml
      run: | 
          CONFIG_YML=frontend/docs-index/_config.yml
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          echo "repo: ${OWNER_PLUS_REPOSITORY}" >> ${CONFIG_YML}
          echo "owner: ${OWNER}" >> ${CONFIG_YML}
          echo "repo_name: ${REPOSITORY}" >> ${CONFIG_YML}

    - name: Store PRs as JSON in _config.yml
      run: |
         PRS=${{needs.get-pull-requests.outputs.PRS}}
         CONFIG_YML=frontend/docs-index/_config.yml
         echo "prs: ${PRS}, CONFIG_YML: ${CONFIG_YML}"
         echo "prs: ${PRS}" >> ${CONFIG_YML}
      
    - name: Compose web site
      run: |
        mkdir -p site
        cp -r frontend/docs-index/* site
        mkdir -p site/storybook
        cp -r frontend/docs-index/storybook_placeholder.html site/storybook/index.html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site # The folder the action should deploy.
        branch: gh-pages
        clean: true # Automatically remove deleted files from the deploy branch

  build-storybook-main:
    name: Storybook (main branch)
    runs-on: ubuntu-latest
    needs: [get-pull-requests, setup-node-and-cache-it, build-basic-site]

    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Build Storybook for main branch
      working-directory: frontend
      run: | # Install npm packages and build the Storybook files
        npm install
        npx build-storybook --docs -o storybook_static

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: frontend/storybook_static # The folder that the build-storybook script generates files.
        clean: true # Automatically remove deleted files from the deploy branch
        target-folder: storybook # The folder that we serve our Storybook files from
    
  build-storybook-for-each-pr:
    name: Storybook (PR ${{ matrix.value.number }}, Branch ${{ matrix.value.headRefName }})
    runs-on: ubuntu-latest
    needs: [setup-node-and-cache-it, build-basic-site]

    strategy:
      matrix:
        value: ${{needs.get-pull-requests.outputs.PRS}}

    steps:
    - name: Debugging Output
      run: |
        echo "matrix.value: ${{ matrix.value }}"
        echo "matrix.value.url: ${{ matrix.value.url }}"
        echo "matrix.value.author: ${{ matrix.value.author }}"
        echo "matrix.value.number: ${{ matrix.value.number }}"
        echo "matrix.value.title:  ${{ matrix.value.title }}"
        echo "matrix.value.headRefName:  ${{ matrix.value.headRefName }}"
   
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.value.headRefName }}
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Build Storybook for PR branch
      working-directory: ./frontend
      run: | # Install npm packages and build the Storybook files
        npm install
        mkdir -p site/prs/${{ matrix.value.number }}/storybook
        mkdir -p storybook-static
        npx build-storybook --docs -o storybook-static
        cp -rv storybook-static/* site/prs/${{ matrix.value.number }}/storybook

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: site/prs/${{ matrix.value.number }}/storybook # The folder that the build-storybook script generates files.
        clean: true # Automatically remove deleted files from the deploy branch
        target-folder: prs/${{ matrix.value.number }}/storybook # The folder that we serve our Storybook files from 
    