# Creates/Resets the gh-pages branch to the intended start state

name: "02-gh-pages-branches: Create or reset branch collection"
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write  # Needed for JamesIves/github-pages-deploy-action@v4

jobs: 
  build-site:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v2

    - name: Append name of site to _config.yml
      run: | 
          CONFIG_YML=frontend/docs-index/_config.yml
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          echo "repo: ${OWNER_PLUS_REPOSITORY}" >> ${CONFIG_YML}
          echo "owner: ${OWNER}" >> ${CONFIG_YML}
          echo "repo_name: ${REPOSITORY}" >> ${CONFIG_YML}

    - name: Get branches from Github api
      run: |
         gh api \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/${{ github.repository }}/branches > branches.json
         cat branches.json
      

    - name: Compose web site
      run: |
        mkdir site
        cp -r frontend/docs-index/* site
        mkdir site/storybook
        cp -r frontend/docs-index/storybook_placeholder.html site/storybook/index.html
        mkdir site/branches    

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site # The folder the action should deploy.
        branch: gh-pages
        clean: true # Automatically remove deleted files from the deploy branch
