name: "03-test-job"
on:
  workflow_dispatch:

jobs:

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson('["a", "b", "c"]'')}}
    steps:
      - run: |
          echo "${{ matrix.value }}"